server:
  port: 6001
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
  instance:
    instance-id: gateway.com
# 访问路径可以显示IP地址
    prefer-ip-address: true
zuul:
  routes:
    user:
      serviceId: provider
      path: /aurora/**
  ignored-services: provider
  prefix: /neu.edu
