server:
  port: 10004
spring:
  application:
    name: fallback
eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/
    register-with-eureka: false
feign:
  hystrix:
    enabled: true
