spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 88775682whz
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
  #      defaultZone: http://eureka.com:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: user-provider2
info.app.name: provider2
info.company.name: neu
info.author.name: whz
logging:
  level:
    root: INFO
